name: Schedule checker

on:
  schedule:
    - cron: "45 */2 * * *"
      timezone: "Europe/Moscow"
    - cron: "45 0-3,23 * * MON-FRI"
      timezone: "Europe/Moscow"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  check-update:
    name: Check & update
    uses: ./.github/workflows/update.yml